---
openapi: 3.0.3
info:
  title: Platform API
  contact:
    name: Spark Solutions
    url: https://sparksolutions.co
    email: we@sparksolutions.co
  description: Spree Platform API
  version: v2
paths:
  "/api/v2/platform/addresses":
    $ref: "./resources/addresses.yaml"
  "/api/v2/platform/addresses/{id}":
    $ref: "resources/address.yaml"
  "/api/v2/platform/adjustments":
    $ref: "resources/adjustments.yaml"
  "/api/v2/platform/adjustments/{id}":
    $ref: "resources/adjustment.yaml"
  "/api/v2/platform/classifications":
    $ref: "resources/classifications.yaml"
  "/api/v2/platform/classifications/{id}":
    $ref: "resources/classification.yaml"
  "/api/v2/platform/cms_pages":
    $ref: "resources/cms_pages.yaml"
  "/api/v2/platform/cms_pages/{id}":
    $ref: "resources/cms_page.yaml"
  "/api/v2/platform/cms_sections":
    $ref: "resources/cms_sections.yaml"
  "/api/v2/platform/cms_sections/{id}":
    $ref: "resources/cms_section.yaml"
  "/api/v2/platform/countries":
    $ref: "resources/countries.yaml"
  "/api/v2/platform/countries/{id}":
    $ref: "resources/country.yaml"
  "/api/v2/platform/digital_links":
    $ref: "resources/digital_links.yaml"
  "/api/v2/platform/digital_links/{id}":
    $ref: "resources/digital_link.yaml"
  "/api/v2/platform/digital_links/{id}/reset":
    $ref: "resources/digital_link_reset.yaml"
  "/api/v2/platform/digitals":
    $ref: "resources/digitals.yaml"
  "/api/v2/platform/digitals/{id}":
    $ref: "resources/digital.yaml"
  "/api/v2/platform/line_items":
    $ref: "resources/line_items.yaml"
  "/api/v2/platform/line_items/{id}":
    $ref: "resources/line_item.yaml"
  "/api/v2/platform/menu_items":
    $ref: "resources/menu_items.yaml"
  "/api/v2/platform/menu_items/{id}":
    $ref: "resources/menu_item.yaml"
  "/api/v2/platform/menu_items/{id}/reposition":
    $ref: "resources/menu_item_reposition.yaml"
  "/api/v2/platform/menus":
    $ref: "resources/menus.yaml"
  "/api/v2/platform/menus/{id}":
    $ref: "resources/menu.yaml"
  "/api/v2/platform/option_types":
   $ref: "resources/option_types.yaml"
  "/api/v2/platform/option_types/{id}":
    $ref: "resources/option_type.yaml"
  "/api/v2/platform/option_values":
    $ref: "resources/option_values.yaml"
  "/api/v2/platform/option_values/{id}":
    $ref: "resources/option_value.yaml"
  "/api/v2/platform/orders":
    $ref: "resources/orders.yaml"
  "/api/v2/platform/orders/{id}":
    $ref: "resources/order.yaml"
  "/api/v2/platform/orders/{id}/advance":
    $ref: "resources/order_advance.yaml"
  "/api/v2/platform/orders/{id}/next":
    $ref: "resources/order_next.yaml"
  "/api/v2/platform/orders/{id}/complete":
    $ref: "resources/order_complete.yaml"
  "/api/v2/platform/orders/{id}/empty":
    $ref: "resources/order_empty.yaml"
  "/api/v2/platform/orders/{id}/approve":
    $ref: "resources/order_approve.yaml"
  "/api/v2/platform/orders/{id}/cancel":
    $ref: "resources/order_cancel.yaml"
  "/api/v2/platform/orders/{id}/use_store_credit":
    $ref: "resources/order_use_store_credit.yaml"
  "/api/v2/platform/orders/{id}/apply_coupon_code":
    $ref: "resources/order_apply_coupon_code.yaml"
  "/api/v2/platform/payment_methods":
    $ref: "resources/payment_methods.yaml"
  "/api/v2/platform/payment_methods/{id}":
    $ref: "resources/payment_method.yaml"
  "/api/v2/platform/payments":
    $ref: "resources/payments.yaml"
  "/api/v2/platform/payments/{id}":
    $ref: "resources/payment.yaml"
  "/api/v2/platform/products":
    $ref: "resources/products.yaml"
  "/api/v2/platform/products/{id}":
    $ref: "resources/product.yaml"
  "/api/v2/platform/promotion_actions":
    $ref: "resources/promotion_actions.yaml"
  "/api/v2/platform/promotion_actions/{id}":
    $ref: "resources/promotion_action.yaml"
  "/api/v2/platform/promotion_categories":
    $ref: "resources/promotion_categories.yaml"
  "/api/v2/platform/promotion_categories/{id}":
    $ref: "resources/promotion_category.yaml"
  "/api/v2/platform/promotion_rules":
    $ref: "resources/promotion_rules.yaml"
  "/api/v2/platform/promotion_rules/{id}":
    $ref: "resources/promotion_rule.yaml"
  "/api/v2/platform/promotions":
    $ref: "resources/promotions.yaml"
  "/api/v2/platform/promotions/{id}":
    $ref: "resources/promotion.yaml"
  "/api/v2/platform/roles":
    $ref: "resources/roles.yaml"
  "/api/v2/platform/roles/{id}":
    $ref: "resources/role.yaml"
  "/api/v2/platform/shipments":
    $ref: "resources/shipments.yaml"
  "/api/v2/platform/shipments/{id}":
    $ref: "resources/shipment.yaml"
  "/api/v2/platform/shipments/{id}/add_item":
    $ref: "resources/shipment_add_item.yaml"
  "/api/v2/platform/shipments/{id}/remove_item":
    $ref: "resources/shipment_remove_item.yaml"
  "/api/v2/platform/shipments/{id}/ready":
    $ref: "resources/shipment_ready.yaml"
  "/api/v2/platform/shipments/{id}/ship":
    $ref: "resources/shipment_ship.yaml"
  "/api/v2/platform/shipments/{id}/cancel":
    $ref: "resources/shipment_cancel.yaml"
  "/api/v2/platform/shipments/{id}/resume":
    $ref: "resources/shipment_resume.yaml"
  "/api/v2/platform/shipments/{id}/pend":
    $ref: "resources/shipment_pend.yaml"
  "/api/v2/platform/shipping_categories":
    $ref: "resources/shipping_categories.yaml"
  "/api/v2/platform/shipping_categories/{id}":
    $ref: "resources/shipping_category.yaml"
  "/api/v2/platform/shipping_methods":
    $ref: "resources/shipping_methods.yaml"
  "/api/v2/platform/shipping_methods/{id}":
    $ref: "resources/shipping_method.yaml"
  "/api/v2/platform/states":
    $ref: "resources/states.yaml"
  "/api/v2/platform/states/{id}":
    $ref: "resources/state.yaml"
  "/api/v2/platform/stock_items":
    $ref: "resources/stock_items.yaml"
  "/api/v2/platform/stock_items/{id}":
    $ref: "resources/stock_item.yaml"
  "/api/v2/platform/stock_locations":
    $ref: "resources/stock_locations.yaml"
  "/api/v2/platform/stock_locations/{id}":
    $ref: "resources/stock_location.yaml"
  "/api/v2/platform/store_credit_categories":
    $ref: "resources/store_credit_categories.yaml"
  "/api/v2/platform/store_credit_categories/{id}":
    $ref: "resources/store_credit_category.yaml"
  "/api/v2/platform/store_credit_types":
    $ref: "resources/store_credit_types.yaml"
  "/api/v2/platform/store_credit_types/{id}":
    $ref: "resources/store_credit_type.yaml"
  "/api/v2/platform/store_credits":
    $ref: "resources/store_credits.yaml"
  "/api/v2/platform/store_credits/{id}":
    $ref: "resources/store_credit.yaml"
  "/api/v2/platform/tax_categories":
    $ref: "resources/tax_categories.yaml"
  "/api/v2/platform/tax_categories/{id}":
    $ref: "resources/tax_category.yaml"
  "/api/v2/platform/tax_rates":
    $ref: "resources/tax_rates.yaml"
  "/api/v2/platform/tax_rates/{id}":
    $ref: "resources/tax_rate.yaml"
  "/api/v2/platform/taxonomies":
    $ref: "resources/taxonomies.yaml"
  "/api/v2/platform/taxonomies/{id}":
    $ref: "resources/taxonomy.yaml"
  "/api/v2/platform/taxons":
    $ref: "resources/taxons.yaml"
  "/api/v2/platform/taxons/{id}":
   $ref: "resources/taxon.yaml"
  "/api/v2/platform/taxons/{id}/reposition":
    $ref: "resources/taxon_reposition.yaml"
  "/api/v2/platform/users":
    $ref: "resources/users.yaml"
  "/api/v2/platform/users/{id}":
    $ref: "resources/user.yaml"
  "/api/v2/platform/variants":
    $ref: "resources/variants.yaml"
  "/api/v2/platform/variants/{id}":
    $ref: "resources/variant.yaml"
  "/api/v2/platform/webhooks/events":
    $ref: "resources/webhook_events.yaml"
  "/api/v2/platform/webhooks/subscribers":
    $ref: "resources/webhook_subscribers.yaml"
  "/api/v2/platform/webhooks/subscribers/{id}":
    $ref: "resources/webhook_subscriber.yaml"
  "/api/v2/platform/wished_items":
    $ref: "resources/wished_items.yaml"
  "/api/v2/platform/wished_items/{id}":
    $ref: "resources/wished_item.yaml"
  "/api/v2/platform/wishlists":
    $ref: "resources/wishlists.yaml"
  "/api/v2/platform/wishlists/{id}":
    $ref: "resources/wishlist.yaml"
  "/api/v2/platform/zones":
    $ref: "resources/zones.yaml"
  "/api/v2/platform/zones/{id}":
    $ref: "resources/zone.yaml"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
tags:
- name: Addresses
- name: Adjustments
- name: Classifications
- name: Countries 
- name: CMS Pages
- name: CMS Sections
- name: Digital Assets
- name: Digital Links
- name: Line Items
- name: Menus
- name: Menu Items
- name: Option Types
- name: Option Values
- name: Orders
- name: Payments
- name: Payment Methods
- name: Products
- name: Promotions
- name: Promotion Actions
- name: Promotion Categories
- name: Promotion Rules
- name: Roles
- name: Shipments
- name: Shipping Categories
- name: Shipping Methods
- name: States
- name: Stock Items
- name: Stock Locations
- name: Store Credit Categories
- name: Store Credit Types
- name: Store Credits
- name: Tax Categories
- name: Tax Rates
- name: Taxons
- name: Taxonomies
- name: Users
- name: Variants
- name: Webhook Events
- name: Webhook Subscribers
- name: Wishlists
- name: Wished Items
- name: Zones
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer